# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  inputs:
    command: 'install'
- task: Npm@1
  displayName: Running Unit Tests
  inputs:
    command: 'custom'
    customCommand: 'test'
- task: Npm@1
  displayName: Running Test Coverage
  inputs:
    command: 'custom'
    customCommand: 'run-script coverage'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/test-results.xml'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '**/cobertura-coverage.xml'