apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-rest.fullname" . }}
stringData:
  {{- if .Values.secrets.kubeconfig }}
  kubeconfig: {{ .Values.secrets.kubeconfig }}
  {{- end }}
  {{- if .Values.secrets.authenticationKey }}
  authenticationKey: {{ .Values.secrets.authenticationKey }}
  {{- end }}
  {{- if .Values.secrets.repositories }}
  repositories: {{ .Values.secrets.repositories }}
  {{- end }}
data:
  {{- if .Values.secrets.base64AuthenticationKey }}
  authenticationKey: {{ .Values.secrets.base64AuthenticationKey }}
  {{- end }}
  {{- if .Values.secrets.base64Repositories }}
  repositories: {{ .Values.secrets.base64Repositories }}
  {{- end }}  