# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker
resources:
- repo: self

variables:
  tag: 'PR-$(Build.SourceBranchName)-B-$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'dockerhub/psbds'
        repository: 'psbds/helm-rest-pr'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        tags: '$(tag)'